### ISSUE TITLE
ArrayIndexOutOfBoundsException bug

### ISSUE THREAD

**Issue by dryangkun** [jarod/qqwry-java#3]
QQWry qqWry = new QQWry();
System.out.println(qqWry.findIP("1.25.36.67"));

error:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 64
	at com.github.jarod.qqwry.QQWry.readString(QQWry.java:147)
	at com.github.jarod.qqwry.QQWry.readSubInfo(QQWry.java:166)
	at com.github.jarod.qqwry.QQWry.readMode2(QQWry.java:135)
	at com.github.jarod.qqwry.QQWry.readIP(QQWry.java:114)
	at com.github.jarod.qqwry.QQWry.findIP(QQWry.java:73)

**Comment by dryangkun** [comment]
2015.4.15号的版本中已经出现了超过64个字节的中文了，需要把QQWry类中的stringBuf加大长度

**Comment by jarod** [comment]
多谢报告问题, 稍后会发布一个修复版本.

**Comment by virjar** [comment]
需要继续加大： 

```java
 IPZone zone = qqwry.findIP("195.123.2.193");
```

```
Index 128 out of bounds for length 128
java.lang.ArrayIndexOutOfBoundsException: Index 128 out of bounds for length 128
	at com.github.jarod.qqwry.QQWry.readString(QQWry.java:196)
	at com.github.jarod.qqwry.QQWry.readSubInfo(QQWry.java:215)
	at com.github.jarod.qqwry.QQWry.readMode2(QQWry.java:183)
	at com.github.jarod.qqwry.QQWry.readIP(QQWry.java:162)
	at com.github.jarod.qqwry.QQWry.findIP(QQWry.java:121)
```

subInfo: 142个字节，大于128
```
Center for Privatization and Economic Reform in Agriculture;Collaborative Project of Iowa State University;Institute of Agrarian Economics
```

**Comment by jarod** [comment]
@virjar 0.10.0版本已经处理了这个问题
