### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jiangchuan2015** [jarod/qqwry-java#5]
使用 2019-08-30 版本的数据，

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1715412953
	at com.github.jarod.qqwry.QQWry.readLong32(QQWry.java:170)
	at com.github.jarod.qqwry.QQWry.readIndex(QQWry.java:131)
	at com.github.jarod.qqwry.QQWry.searchIndex(QQWry.java:221)
	at com.github.jarod.qqwry.QQWry.findIP(QQWry.java:114)

**Comment by jarod** [comment]
测试了一下2019-08-30的数据库没有报错，你查询的是什么IP

**Comment by jiangchuan2015** [comment]
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)


-------------------------------------------------------------------------------------
public static void main(String[] args) throws IOException {
        QQWry qqwry = new QQWry();

        try {
            String myIP1 = "127.0.0.1";
            IPZone ipzone1 = qqwry.findIP(myIP1);
            System.out.printf("%s, %s", ipzone1.getMainInfo(), ipzone1.getSubInfo());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        try {
            String myIP2 = "182.138.228.240";
            IPZone ipzone2 = qqwry.findIP(myIP2);
            System.out.printf("%s, %s", ipzone2.getMainInfo(), ipzone2.getSubInfo());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

-------------------------------------------------------------------------------------
java.lang.ArrayIndexOutOfBoundsException: -1715412953
	at com.github.jarod.qqwry.QQWry.readLong32(QQWry.java:170)
	at com.github.jarod.qqwry.QQWry.readIndex(QQWry.java:131)
	at com.github.jarod.qqwry.QQWry.searchIndex(QQWry.java:221)
	at com.github.jarod.qqwry.QQWry.findIP(QQWry.java:114)

java.lang.ArrayIndexOutOfBoundsException: -1715412953
	at com.github.jarod.qqwry.QQWry.readLong32(QQWry.java:170)
	at com.github.jarod.qqwry.QQWry.readIndex(QQWry.java:131)
	at com.github.jarod.qqwry.QQWry.searchIndex(QQWry.java:221)
	at com.github.jarod.qqwry.QQWry.findIP(QQWry.java:114)

**Comment by jiangchuan2015** [comment]
<dependency>
            <groupId>com.github.jarod</groupId>
            <artifactId>qqwry-java</artifactId>
            <version>0.7.2</version>
        </dependency>

**Comment by jarod** [comment]
测试了你查询的IP是没问题的，可能是你的CLASSPATH中有一个格式跟纯真数据库不兼容的qqwry.dat文件，你可以尝试用下面的方法指定qqwry.dat文件初始化
```java
QQWry qqwry = new QQWry(Paths.get("path/to/qqwry.dat"));
```

**Comment by jiangchuan2015** [comment]
OS 名称: Microsoft Windows 10 专业版
OS 版本:  10.0.17763 暂缺 Build 17763

IDEA 2019.01

**Comment by jiangchuan2015** [comment]
非常感谢，确实是 classpath 下的 dat 文件有问题！
