### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 672264329

### ISSUE THREAD

**Issue by sxm20074428** [jarod/qqwry-java#7]
at com.github.jarod.qqwry.QQWry.readLong32(QQWry.java:170)
	at com.github.jarod.qqwry.QQWry.readIndex(QQWry.java:131)
	at com.github.jarod.qqwry.QQWry.searchIndex(QQWry.java:221)
	at com.github.jarod.qqwry.QQWry.findIP(QQWry.java:114)

**Comment by jarod** [comment]
@sxm20074428  使用什么版本的数据库，查找什么IP时出现的？

**Comment by jarod** [comment]
@sxm20074428  看看是不是这个问题 #5

**Comment by daiyun169** [comment]
0.8.0 拷贝qqwry.dat 到 classpath 

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1613420847 out of bounds for length 18679300
	at com.github.jarod.qqwry.QQWry.readLong32(QQWry.java:170)
	at com.github.jarod.qqwry.QQWry.readIndex(QQWry.java:131)
	at com.github.jarod.qqwry.QQWry.searchIndex(QQWry.java:221)
	at com.github.jarod.qqwry.QQWry.findIP(QQWry.java:114)
	at com.github.jarod.qqwry.QQWry.parseDatabaseVersion(QQWry.java:257)
	at com.github.jarod.qqwry.QQWry.<init>(QQWry.java:87)
	at com.zmaing.test.main(test.java:15)
